# -*- coding: utf-8 -*-
"""Food_recipe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPyh15NMN4LwwJHgU5dxt_vXcuE8HD7x
"""

import os
HOME = os.getcwd()
print(HOME)

# Pip install method (recommended)

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
!mkdir {HOME}/datasets
# %cd {HOME}/datasets

!pip install roboflow --quiet

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="yy4yNFaODSlGo8Xe9QvI")
project = rf.workspace("my-space-xiszl").project("food-a2sl5")
version = project.version(1)
dataset = version.download("yolov8")

from ultralytics import YOLO

# Load the YOLOv8 model (replace 'path/to/your_model.pt' with your model path if custom)
model = YOLO("yolov8n.pt")  # or use your custom model, e.g., "best.pt"

# Replace with the path to your test image
image_path = "/content/download (5).jpg"

# Perform prediction
results = model.predict(source=image_path, save=True, conf=0.5)  # Set confidence threshold as needed

from PIL import Image
import matplotlib.pyplot as plt

# Load and display the prediction image
output_image_path = "runs/detect/predict/download (5).jpg"  # Adjust the path if needed
output_image = Image.open(output_image_path)
plt.imshow(output_image)
plt.axis("off")
plt.show()